version: '3.9'

services:
  client:
    build:
      context: ../
      dockerfile: docker/node/Dockerfile
    working_dir: /application
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - network

networks:
  network:
    name: network
    external: true
